### ISSUE TITLE
code issues

### ISSUE THREAD

**Issue by floschne** [Remorax/VeeAlign#5]
Hi,

first of all thank you very much for sharing the code, database and models! :)

Unfortunately, your code is not runnable with out quit a bit of modifying and making assumptions. I guess you forgot to push the latest version of the `src/train.py` and `src/test.py` files when you updated the `DataParser` or the `src/data_preprocessing.py` file in the last commmit (https://github.com/Remorax/VeeAlign/commit/5d5d214dbbd89b5d76703c1d7da51cfeb82ac128) ? I'm guessing this because in the `train.py` and `test.py` files, the way the  `DataParser` gets instantiated, does not match the signature of the init function. Further, the return values of the `DataParser.process` do not match the values you expect from the calls to the function in the `train.py` and `test.py` files.

Can you please provide the corrected files :) ?

Thank you very much in advance!

**Comment by floschne** [comment]
@Remorax @shanmukh5

**Comment by Remorax** [comment]
Hi @floschne thanks for your interest in our work, and for pointing out this crucial bug introduced in the last few commits. I have now [fixed this](https://github.com/Remorax/VeeAlign/commit/a46d3dc93c5f6f9c45826b41358f9471c11e1755) on master and tested it to work fine. So I am now closing this issue, but of course please feel free to reach out in case of anything else.

Thanks again!

Side note: You may want to pull once again from master, since I have also added a couple of new features that could improve convergence (early stopping, saving best model etc.)

**Comment by floschne** [comment]
@Remorax Thank you very much! :)
